spring:
  application:
    name: Filmorate
  config:
    import: classpath:application-director.yml
  jackson:
    serialization:
      write-durations-as-timestamps: true
  sql:
    init:
      mode: always
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    ru.yandex.practicum: debug
