director:
  insert-director: "INSERT INTO directors (director_name) VALUES (?)"
  delete-director-by-id: "DELETE FROM directors WHERE director_id = "
  get-id-by-director: "SELECT director_id FROM directors WHERE director_name = ?"
  get-director-by-id : "SELECT * FROM directors WHERE director_id = ?"
  get-all-IDs: "SELECT director_id FROM directors"
  reset-primary-key: "ALTER TABLE directors ALTER COLUMN director_id RESTART WITH 1"
  update-director: "UPDATE directors SET director_name = ? WHERE director_id = ?"







